#include <unios/keymap.h>

#define KEYMAP_ENTRY(raw, no_shift_key, shift_key) \
    { (raw), (no_shift_key), (shift_key) }

keymap_entry_t keymap[NR_SCAN_CODES] = {
    KEYMAP_ENTRY(0, 0, 0),                     //<! 0x00 - none
    KEYMAP_ENTRY(ESC, ESC, 0),                 //<! 0x01 - ESC
    KEYMAP_ENTRY('1', '!', 0),                 //<! 0x02 - '1'
    KEYMAP_ENTRY('2', '@', 0),                 //<! 0x03 - '2'
    KEYMAP_ENTRY('3', '#', 0),                 //<! 0x04 - '3'
    KEYMAP_ENTRY('4', '$', 0),                 //<! 0x05 - '4'
    KEYMAP_ENTRY('5', '%', 0),                 //<! 0x06 - '5'
    KEYMAP_ENTRY('6', '^', 0),                 //<! 0x07 - '6'
    KEYMAP_ENTRY('7', '&', 0),                 //<! 0x08 - '7'
    KEYMAP_ENTRY('8', '*', 0),                 //<! 0x09 - '8'
    KEYMAP_ENTRY('9', '(', 0),                 //<! 0x0A - '9'
    KEYMAP_ENTRY('0', ')', 0),                 //<! 0x0B - '0'
    KEYMAP_ENTRY('-', '_', 0),                 //<! 0x0C - '-'
    KEYMAP_ENTRY('=', '+', 0),                 //<! 0x0D - '='
    KEYMAP_ENTRY(BACKSPACE, BACKSPACE, 0),     //<! 0x0E - BS
    KEYMAP_ENTRY(TAB, TAB, 0),                 //<! 0x0F - TAB
    KEYMAP_ENTRY('q', 'Q', 0),                 //<! 0x10 - 'q'
    KEYMAP_ENTRY('w', 'W', 0),                 //<! 0x11 - 'w'
    KEYMAP_ENTRY('e', 'E', 0),                 //<! 0x12 - 'e'
    KEYMAP_ENTRY('r', 'R', 0),                 //<! 0x13 - 'r'
    KEYMAP_ENTRY('t', 'T', 0),                 //<! 0x14 - 't'
    KEYMAP_ENTRY('y', 'Y', 0),                 //<! 0x15 - 'y'
    KEYMAP_ENTRY('u', 'U', 0),                 //<! 0x16 - 'u'
    KEYMAP_ENTRY('i', 'I', 0),                 //<! 0x17 - 'i'
    KEYMAP_ENTRY('o', 'O', 0),                 //<! 0x18 - 'o'
    KEYMAP_ENTRY('p', 'P', 0),                 //<! 0x19 - 'p'
    KEYMAP_ENTRY('[', '{', 0),                 //<! 0x1A - '['
    KEYMAP_ENTRY(']', '}', 0),                 //<! 0x1B - ']'
    KEYMAP_ENTRY(ENTER, ENTER, PAD_ENTER),     //<! 0x1C - CR/LF
    KEYMAP_ENTRY(CTRL_L, CTRL_L, CTRL_R),      //<! 0x1D - l. Ctrl
    KEYMAP_ENTRY('a', 'A', 0),                 //<! 0x1E - 'a'
    KEYMAP_ENTRY('s', 'S', 0),                 //<! 0x1F - 's'
    KEYMAP_ENTRY('d', 'D', 0),                 //<! 0x20 - 'd'
    KEYMAP_ENTRY('f', 'F', 0),                 //<! 0x21 - 'f'
    KEYMAP_ENTRY('g', 'G', 0),                 //<! 0x22 - 'g'
    KEYMAP_ENTRY('h', 'H', 0),                 //<! 0x23 - 'h'
    KEYMAP_ENTRY('j', 'J', 0),                 //<! 0x24 - 'j'
    KEYMAP_ENTRY('k', 'K', 0),                 //<! 0x25 - 'k'
    KEYMAP_ENTRY('l', 'L', 0),                 //<! 0x26 - 'l'
    KEYMAP_ENTRY(';', ':', 0),                 //<! 0x27 - ';'
    KEYMAP_ENTRY('\'', '"', 0),                //<! 0x28 - '\''
    KEYMAP_ENTRY('`', '~', 0),                 //<! 0x29 - '`'
    KEYMAP_ENTRY(SHIFT_L, SHIFT_L, 0),         //<! 0x2A - l. SHIFT
    KEYMAP_ENTRY('\\', '|', 0),                //<! 0x2B - '\'
    KEYMAP_ENTRY('z', 'Z', 0),                 //<! 0x2C - 'z'
    KEYMAP_ENTRY('x', 'X', 0),                 //<! 0x2D - 'x'
    KEYMAP_ENTRY('c', 'C', 0),                 //<! 0x2E - 'c'
    KEYMAP_ENTRY('v', 'V', 0),                 //<! 0x2F - 'v'
    KEYMAP_ENTRY('b', 'B', 0),                 //<! 0x30 - 'b'
    KEYMAP_ENTRY('n', 'N', 0),                 //<! 0x31 - 'n'
    KEYMAP_ENTRY('m', 'M', 0),                 //<! 0x32 - 'm'
    KEYMAP_ENTRY(',', '<', 0),                 //<! 0x33 - ','
    KEYMAP_ENTRY('.', '>', 0),                 //<! 0x34 - '.'
    KEYMAP_ENTRY('/', '?', PAD_SLASH),         //<! 0x35 - '/'
    KEYMAP_ENTRY(SHIFT_R, SHIFT_R, 0),         //<! 0x36 - r. SHIFT
    KEYMAP_ENTRY('*', '*', 0),                 //<! 0x37 - '*'
    KEYMAP_ENTRY(ALT_L, ALT_L, ALT_R),         //<! 0x38 - ALT
    KEYMAP_ENTRY(' ', ' ', 0),                 //<! 0x39 - ' '
    KEYMAP_ENTRY(CAPS_LOCK, CAPS_LOCK, 0),     //<! 0x3A - CapsLock
    KEYMAP_ENTRY(F1, F1, 0),                   //<! 0x3B - F1
    KEYMAP_ENTRY(F2, F2, 0),                   //<! 0x3C - F2
    KEYMAP_ENTRY(F3, F3, 0),                   //<! 0x3D - F3
    KEYMAP_ENTRY(F4, F4, 0),                   //<! 0x3E - F4
    KEYMAP_ENTRY(F5, F5, 0),                   //<! 0x3F - F5
    KEYMAP_ENTRY(F6, F6, 0),                   //<! 0x40 - F6
    KEYMAP_ENTRY(F7, F7, 0),                   //<! 0x41 - F7
    KEYMAP_ENTRY(F8, F8, 0),                   //<! 0x42 - F8
    KEYMAP_ENTRY(F9, F9, 0),                   //<! 0x43 - F9
    KEYMAP_ENTRY(F10, F10, 0),                 //<! 0x44 - F10
    KEYMAP_ENTRY(NUM_LOCK, NUM_LOCK, 0),       //<! 0x45 - NumLock
    KEYMAP_ENTRY(SCROLL_LOCK, SCROLL_LOCK, 0), //<! 0x46 - ScrLock
    KEYMAP_ENTRY(PAD_HOME, '7', HOME),         //<! 0x47 - Home
    KEYMAP_ENTRY(PAD_UP, '8', UP),             //<! 0x48 - CurUp
    KEYMAP_ENTRY(PAD_PAGEUP, '9', PAGEUP),     //<! 0x49 - PgUp
    KEYMAP_ENTRY(PAD_MINUS, '-', 0),           //<! 0x4A - '-'
    KEYMAP_ENTRY(PAD_LEFT, '4', LEFT),         //<! 0x4B - Left
    KEYMAP_ENTRY(PAD_MID, '5', 0),             //<! 0x4C - MID
    KEYMAP_ENTRY(PAD_RIGHT, '6', RIGHT),       //<! 0x4D - Right
    KEYMAP_ENTRY(PAD_PLUS, '+', 0),            //<! 0x4E - '+'
    KEYMAP_ENTRY(PAD_END, '1', END),           //<! 0x4F - End
    KEYMAP_ENTRY(PAD_DOWN, '2', DOWN),         //<! 0x50 - Down
    KEYMAP_ENTRY(PAD_PAGEDOWN, '3', PAGEDOWN), //<! 0x51 - PgDown
    KEYMAP_ENTRY(PAD_INS, '0', INSERT),        //<! 0x52 - Insert
    KEYMAP_ENTRY(PAD_DOT, '.', DELETE),        //<! 0x53 - Delete
    KEYMAP_ENTRY(0, 0, 0),                     //<! 0x54 - Enter
    KEYMAP_ENTRY(0, 0, 0),                     //<! 0x55 - ???
    KEYMAP_ENTRY(0, 0, 0),                     //<! 0x56 - ???
    KEYMAP_ENTRY(F11, F11, 0),                 //<! 0x57 - F11
    KEYMAP_ENTRY(F12, F12, 0),                 //<! 0x58 - F12
    KEYMAP_ENTRY(0, 0, 0),                     //<! 0x59 - ???
    KEYMAP_ENTRY(0, 0, 0),                     //<! 0x5A - ???
    KEYMAP_ENTRY(0, 0, GUI_L),                 //<! 0x5B - ???
    KEYMAP_ENTRY(0, 0, GUI_R),                 //<! 0x5C - ???
    KEYMAP_ENTRY(0, 0, APPS),                  //<! 0x5D - ???
    KEYMAP_ENTRY(0, 0, 0),                     //<! 0x5E - ???
    KEYMAP_ENTRY(0, 0, 0),                     //<! 0x5F - ???
    KEYMAP_ENTRY(0, 0, 0),                     //<! 0x60 - ???
    KEYMAP_ENTRY(0, 0, 0),                     //<! 0x61 - ???
    KEYMAP_ENTRY(0, 0, 0),                     //<! 0x62 - ???
    KEYMAP_ENTRY(0, 0, 0),                     //<! 0x63 - ???
    KEYMAP_ENTRY(0, 0, 0),                     //<! 0x64 - ???
    KEYMAP_ENTRY(0, 0, 0),                     //<! 0x65 - ???
    KEYMAP_ENTRY(0, 0, 0),                     //<! 0x66 - ???
    KEYMAP_ENTRY(0, 0, 0),                     //<! 0x67 - ???
    KEYMAP_ENTRY(0, 0, 0),                     //<! 0x68 - ???
    KEYMAP_ENTRY(0, 0, 0),                     //<! 0x69 - ???
    KEYMAP_ENTRY(0, 0, 0),                     //<! 0x6A - ???
    KEYMAP_ENTRY(0, 0, 0),                     //<! 0x6B - ???
    KEYMAP_ENTRY(0, 0, 0),                     //<! 0x6C - ???
    KEYMAP_ENTRY(0, 0, 0),                     //<! 0x6D - ???
    KEYMAP_ENTRY(0, 0, 0),                     //<! 0x6E - ???
    KEYMAP_ENTRY(0, 0, 0),                     //<! 0x6F - ???
    KEYMAP_ENTRY(0, 0, 0),                     //<! 0x70 - ???
    KEYMAP_ENTRY(0, 0, 0),                     //<! 0x71 - ???
    KEYMAP_ENTRY(0, 0, 0),                     //<! 0x72 - ???
    KEYMAP_ENTRY(0, 0, 0),                     //<! 0x73 - ???
    KEYMAP_ENTRY(0, 0, 0),                     //<! 0x74 - ???
    KEYMAP_ENTRY(0, 0, 0),                     //<! 0x75 - ???
    KEYMAP_ENTRY(0, 0, 0),                     //<! 0x76 - ???
    KEYMAP_ENTRY(0, 0, 0),                     //<! 0x77 - ???
    KEYMAP_ENTRY(0, 0, 0),                     //<! 0x78 - ???
    KEYMAP_ENTRY(0, 0, 0),                     //<! 0x78 - ???
    KEYMAP_ENTRY(0, 0, 0),                     //<! 0x7A - ???
    KEYMAP_ENTRY(0, 0, 0),                     //<! 0x7B - ???
    KEYMAP_ENTRY(0, 0, 0),                     //<! 0x7C - ???
    KEYMAP_ENTRY(0, 0, 0),                     //<! 0x7D - ???
    KEYMAP_ENTRY(0, 0, 0),                     //<! 0x7E - ???
    KEYMAP_ENTRY(0, 0, 0),                     //<! 0x7F - ???
};
