SOURCE_DEPS_FILE := $(OBJDIR)/.cache/.deps
CACHED_FILES     += $(SOURCE_DEPS_FILE)

MERGE_SCRIPT := misc/mergedep.pl

OBJDIRS := $(sort $(dir $(OBJECT_FILES)))

# merge source deps generated by gcc
$(SOURCE_DEPS_FILE): $(foreach dir,$(OBJDIRS),$(wildcard $(dir)*.d))
	@echo -ne "[PROC] analyze source deps\r"
	@mkdir -p $(@D)
	@perl $(MERGE_SCRIPT) $@ $^
	@echo -e "\e[1K\r\e[32m[DONE]\e[0m analyze source deps"

-include $(SOURCE_DEPS_FILE)
