SOURCE_DEPS_FILE := $(OBJDIR).cache/.deps
CACHED_FILES     += $(SOURCE_DEPS_FILE)

MERGE_SCRIPT := scripts/mergedep.pl

OBJDIRS := $(sort $(dir $(OBJECT_FILES)))

# merge source deps generated by gcc
# NOTE: foreach always return something, including empty str, and this rules
# will always be executed, here we do extra work to reduce the load
$(SOURCE_DEPS_FILE): $(foreach dir,$(OBJDIRS),$(wildcard $(dir)*.d))
	@\
	if [ ! -z "$^" ]; then                         \
		$(call begin-job,analyze source deps,);    \
		mkdir -p $(@D);                            \
		perl $(MERGE_SCRIPT) $@.swp $^;            \
		cmp -s $@ $@.swp || cp $@.swp $@;          \
		$(call end-job,done,analyze source deps,); \
	fi

-include $(SOURCE_DEPS_FILE)
